language: go
compiler: clang
sudo: required

addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
    - libclang-dev
    - libopus-dev
    - libsodium-dev
    - libvpx-dev

go:
#- 1.4.x
#- 1.5.x
#- 1.6.x
#- 1.7.x
#- 1.8.x
#- 1.9.x
- master

install:
# Add libclang's lib directory to search path for Go.
- export CGO_LDFLAGS="-L`llvm-config --libdir`"
# Install toxcore.
- git clone https://github.com/TokTok/c-toxcore
- cd c-toxcore
- cmake .
- make -j2
- sudo make install
- cd ..
- sudo ldconfig > /dev/null
# Install Go packages.
- go get github.com/bitly/go-simplejson
- go get github.com/go-clang/v3.8/clang
- go get github.com/kitech/godsts/maps/hashbidimap
- go get github.com/kitech/godsts/maps/hashmap
- go get github.com/kitech/godsts/sets/hashset
- go get github.com/masatana/go-textdistance
- go get github.com/sasha-s/go-deadlock
- go get github.com/sysr-q/gopp/gopp
- go get github.com/xrash/smetrics
